### ISSUE TITLE
WIndows 10, can not load dll's

### ISSUE THREAD

**Issue by elucidator** [NicholasAStuart/myo-java#10]
Nicholas,

I'm starting out with the myo on java. Got WIndows 10 and JDK 8 running, but i cant load the DLL's.

I specified the -Djava.library.path=c:\tmp and placed the 64 bit DLL's there. You know of any limitations on WIndows 10?

Below is the stack trace I have, Two thing i find strange, first the name of the JNI library, it ends with 64 (and yes did a copy with that name as well) ANd it tells me its not a valid Win32 application?

Suggestions.

(And no i do not have C compiler running :-) )

Unable to load myo64 from system directories.
Unable to load myo32 from system directories.
Unable to load myo64.dll from directory C:\XXX\Temp.
java.lang.UnsatisfiedLinkError: C:\XXXX\Temp\JNIJavaMyoLib64.dll: %1 is not a valid Win32 application
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1938)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1854)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at com.thalmic.myo.Hub.copyAndLoadX64FromTemp(Hub.java:194)
	at com.thalmic.myo.Hub.loadJniResources(Hub.java:67)
	at com.thalmic.myo.Hub.<init>(Hub.java:27)
	at com.thalmic.myo.example.HelloMyo.main(HelloMyo.java:16)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)
Unable to load myo32.dll from directory C:\XXXX\Temp.
java.lang.UnsatisfiedLinkError: C:\XXXX\Temp\myo32.dll: Can't load IA 32-bit .dll on a AMD 64-bit platform
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1938)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1854)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at com.thalmic.myo.Hub.copyAndLoadWin32FromTemp(Hub.java:222)
	at com.thalmic.myo.Hub.loadJniResources(Hub.java:69)
	at com.thalmic.myo.Hub.<init>(Hub.java:27)
	at com.thalmic.myo.example.HelloMyo.main(HelloMyo.java:16)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)
Exception in thread "main" java.lang.UnsatisfiedLinkError: Could Not Load myo and myo-java libs
	at com.thalmic.myo.Hub.loadJniResources(Hub.java:71)
	at com.thalmic.myo.Hub.<init>(Hub.java:27)
	at com.thalmic.myo.example.HelloMyo.main(HelloMyo.java:16)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)

**Comment by DanielGoP** [comment]
I have the same problem.

**Comment by NicholasAStuart** [comment]
I haven't tested on Windows 10, so I'm not sure if it will work or not. I'll try testing this in the next few days once I get a machine capable of testing.

**Comment by NicholasAStuart** [comment]
What version are you using? Testing on My Windows 10, I don't have any issues. You shouldn't have to specify -Djava.library.path=c:\tmp, as the JAR should install it already for you.

**Comment by drakator** [comment]
I have the same problem
our JNI was warking fine with previosu versions of windows and suddently started to be unable to load dll on various custommers running windows 10
most of customers working fine but some of them are unable to load DLL
I have no idea what is happening...

**Comment by Dustinhoefer** [comment]
Same, any idea why the lib can not be found?
