### ISSUE TITLE
JNIJavaMyoLib64.dll: Can't find dependent libraries

### ISSUE THREAD

**Issue by alexey-schroeder** [NicholasAStuart/myo-java#8]
Hallo, I have the exeption:

Unable to load myo64 from system directories.
Unable to load myo32 from system directories.
Unable to load myo64.dll from directory C:\Users\Alex\AppData\Local\Temp.
java.lang.UnsatisfiedLinkError: C:\Users\Alex\AppData\Local\Temp\JNIJavaMyoLib64.dll: Can't find dependent libraries
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1929)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1847)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1119)
	at com.thalmic.myo.Hub.copyAndLoadX64FromTemp(Hub.java:194)
	at com.thalmic.myo.Hub.loadJniResources(Hub.java:67)
	at com.thalmic.myo.Hub.<init>(Hub.java:27)
	at com.thalmic.myo.example.HelloMyo.main(HelloMyo.java:16)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:134)
Unable to load myo32.dll from directory C:\Users\Alex\AppData\Local\Temp.
java.lang.UnsatisfiedLinkError: C:\Users\Alex\AppData\Local\Temp\myo32.dll: Can't load IA 32-bit .dll on a AMD 64-bit platform
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1929)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1847)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1119)
	at com.thalmic.myo.Hub.copyAndLoadWin32FromTemp(Hub.java:222)
	at com.thalmic.myo.Hub.loadJniResources(Hub.java:69)
	at com.thalmic.myo.Hub.<init>(Hub.java:27)
	at com.thalmic.myo.example.HelloMyo.main(HelloMyo.java:16)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:134)
Exception in thread "main" java.lang.UnsatisfiedLinkError: Could Not Load myo and myo-java libs
	at com.thalmic.myo.Hub.loadJniResources(Hub.java:71)
	at com.thalmic.myo.Hub.<init>(Hub.java:27)
	at com.thalmic.myo.example.HelloMyo.main(HelloMyo.java:16)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:134) 

The file "JNIJavaMyoLib64.dll" doesn't present in path "myo-java-master\src\main\resources\x64". If i change the line number 194 in Hub.java "System.loadLibrary("JNIJavaMyoLib64");" to "System.loadLibrary("JNIJavaMyoLib");"  is the exeption still there.

Could you get the correct library? 
Thanks in advance

Alexey

**Comment by NicholasAStuart** [comment]
The file doesn't have to JNIJavaMyoLib64 doesn't have to be present in the JAR. If you see line 189 of Hub.java it's loading the DLL JNIJavaMyoLib.dll and saving it out to %TEMP%/JNIJavaMyoLib64.dll, then loading JNIJavaMyoLib64.dll.

**Comment by alexey-schroeder** [comment]
Thanks for quickly reply. I have found the reason of the problem. The library JNIJavaMyoLib.dll has dependency from library msvcp100.dll. If the library there isn't is the UnsatisfiedLinkError thrown. Could you set the msvcp100.dll in your jar?

**Comment by NicholasAStuart** [comment]
Thanks for reporting back the issue. I'll try to include a troubleshooting section in the README that highlights that that may be an issue. 

As for including it, I could, but that would increase the already large JAR size, as well as mean that I'll have to maintain the versioning if a new one is needed, and be responsible for an outside JAR that may have separate licensing issues. I think a troubleshooting section should be enough for now.

Thanks again!
